# Ghost 2025

# Ubuntu 22.04
# ROS2 Humble

FROM osrf/ros:humble-desktop

WORKDIR /root/

RUN apt-get update
RUN apt-get install apt-utils software-properties-common -y

RUN apt install git tmux tmuxinator -y
## ROS2 utils

RUN apt-get install python3-rosdep  \
                python3-pip     \
                python3-colcon-common-extensions \
                python3-colcon-mixin \
                ros-dev-tools -y

RUN apt-get install python3-flake8 \
                python3-flake8-builtins  \
                python3-flake8-comprehensions \
                python3-flake8-docstrings \
                python3-flake8-import-order \
                python3-flake8-quotes -y

RUN pip3 install pylint
RUN pip3 install flake8==4.0.1
RUN pip3 install pycodestyle==2.8
RUN pip3 install cmakelint cpplint

RUN apt-get install cppcheck lcov -y

RUN colcon mixin update default
RUN rm -rf log # remove log folder

RUN pip3 install colcon-lcov-result cpplint cmakelint
RUN pip3 install PySimpleGUI-4-foss

RUN apt install git tmux tmuxinator -y
RUN apt install ros-humble-tf-transformations

RUN pip install "numpy<1.24"

# Agent forwarding during docker build https://stackoverflow.com/questions/43418188/ssh-agent-forwarding-during-docker-build
RUN apt-get update
ENV DOCKER_BUILDKIT=1
RUN apt-get install -y openssh-client
ENV GIT_SSH_COMMAND="ssh -v"
USER root

RUN mkdir -p -m 0600 ~/.ssh/ && ssh-keyscan github.com >> ~/.ssh/known_hosts
ARG HOME=/root

WORKDIR $HOME

# PX4 Offboard dependencies
RUN git clone https://github.com/eProsima/Micro-XRCE-DDS-Agent.git
WORKDIR $HOME/Micro-XRCE-DDS-Agent
RUN mkdir build
WORKDIR $HOME/Micro-XRCE-DDS-Agent/build
RUN cmake ..
RUN make
RUN sudo make install
RUN sudo ldconfig /usr/local/lib/

WORKDIR $HOME/tutorials/src/
RUN git clone -b release/1.15 https://github.com/PX4/px4_msgs.git
RUN git clone https://github.com/PX4/px4_ros_com.git
RUN git clone https://github.com/ros/executive_smach.git
RUN --mount=type=ssh git clone git@github.com:ghost-drones/eletroquad25_sm.git
WORKDIR $HOME/tutorials
RUN rosdep install --from-paths src --ignore-src -r -y
RUN . /opt/ros/$ROS_DISTRO/setup.sh && colcon build --symlink-install
RUN echo "source /root/tutorials/install/setup.bash" >> ~/.bashrc
RUN echo "export AEROSTACK2_TUTORIAL_PATH=/root/tutorials/src/aerostack2_tutorial" >> ~/.bashrc
RUN sudo apt-get install nano

# Ghost AS2 tutorial
WORKDIR $HOME/tutorials/src
RUN --mount=type=ssh git clone -b eletroquad25 git@github.com:ghost-drones/aerostack2_tutorial.git

COPY to_copy/tmux $HOME/.tmux.conf
COPY to_copy/aliases $HOME/.bash_aliases

WORKDIR $HOME/tutorials
RUN colcon build