/**:
  # Global Parameters
  ros__parameters:
    use_sim_time: true
    tf_timeout_threshold: 0.05

/**:
  # Basic Robotics Functions
  platform:
    ros__parameters:
      cmd_freq: 100.0  # Hz of platform commands send
      info_freq: 10.0  # Hz of platform info publish
      max_thrust: 15.0  # N
      min_thrust: 0.15  # N
      external_odom: false  # Use external odometry source

  # State Estimator
  state_estimator:
    ros__parameters:
      plugin_name: "raw_odometry"
      #use_gazebo_tf: true
      #plugin_name: "ground_truth"
      ## Outdoor (GPS)
      #use_gps: true
      #set_origin_on_start: true # Set origin on start

  # Behaviors Motion
  TakeoffBehavior:
    ros__parameters:
      # takeoff_plugin_name: "takeoff_plugin_speed"
      takeoff_plugin_name: "takeoff_plugin_position"
      # takeoff_plugin_name: "takeoff_plugin_trajectory"
      # takeoff_plugin_name: "takeoff_plugin_platform"
  LandBehavior:
    ros__parameters:
      land_plugin_name: "land_plugin_speed"
      # land_plugin_name: "land_plugin_trajectory"
  GoToBehavior:
    ros__parameters:
      go_to_plugin_name: "go_to_plugin_position"
      # go_to_plugin_name: "go_to_plugin_trajectory"
  FollowPathBehavior:
    ros__parameters:
      follow_path_plugin_name: "follow_path_plugin_position"
      # follow_path_plugin_name: "follow_path_plugin_trajectory"

# Specific Parameters for each drone
x500_px4:
  platform:
    ros__parameters:
      fmu_prefix: /x500_px4
      tgt_system: 1

#  mavros/mavros_node:
#    ros__parameters:
#      fcu_url: "udp://:14540@127.0.0.1:14557"
#      tgt_system: 1