world_name: empty
origin:
  latitude: 40.4405287
  longitude: -3.6898277
  altitude: 100.0
drones:
- model_type: quadrotor_base
  model_name: drone0
  flight_time: 60
  xyz:
  - 0.0
  - 0.0
  - 0.3
  payload:
  - model_type: gps
    model_name: gps
  - model_type: gimbal_speed
    model_name: gimbal
    payload:
      model_type: hd_camera
      model_name: camera
objects:
- model_name: base_inicial
  model_type: circulo_azul
  xyz:
  - 0.0
  - 0.0
  - 0.01
- model_name: barra_1
  model_type: barra_rosa
  xyz:
  - 1.05
  - -3.14
  - 0.0
- model_name: barra_2
  model_type: barra_azul
  xyz:
  - 2.77
  - -1.35
  - 0.0
- model_name: barra_3
  model_type: barra_preto_fosco
  xyz:
  - 3.54
  - -0.8
  - 0.0
- model_name: barra_4
  model_type: barra_azul
  xyz:
  - 4.97
  - 1.39
  - 0.0
- model_name: barra_5
  model_type: barra_preto_fosco
  xyz:
  - 5.93
  - 2.2
  - 0.0
- model_name: base_final
  model_type: cruz_rosa
  xyz:
  - 7.99
  - -1.95
  - 0.01
