drones:
- flight_time: 60
  model_name: x500_px4
  model_type: x500_px4
  payload:
  - model_name: gps
    model_type: gps
  - model_name: camera
    model_type: hd_camera
    rpy:
    - 0.0
    - 0.0
    - 0.0
    xyz:
    - 0.04
    - 0.0
    - -0.1
  - model_name: gancho
    model_type: gancho
    xyz:
    - 0.0
    - 0.0
    - -0.05
  xyz:
  - -12.5
  - -10
  - 0.5
objects:
- model_name: eletroquad_arena
  model_type: eletroquad_arena
  rpy:
  - 0.0
  - 0.0
  - 0.0
  xyz:
  - 0.0
  - 0.0
  - 0.1
- model_name: base_inicial_slalom
  model_type: circulo_azul
  xyz:
  - -12.5
  - -10
  - 0.11
- model_name: barra_1
  model_type: barra_rosa
  object_bridges:
  - pose
  xyz:
  - -8.71
  - -10.24
  - 0.1
- model_name: barra_2
  model_type: barra_azul
  object_bridges:
  - pose
  xyz:
  - -5.65
  - -7.58
  - 0.1
- model_name: barra_3
  model_type: barra_preto_fosco
  object_bridges:
  - pose
  xyz:
  - -0.66
  - -12.18
  - 0.1
- model_name: barra_4
  model_type: barra_vermelha
  object_bridges:
  - pose
  xyz:
  - 3.84
  - -11.45
  - 0.1
- model_name: marker_1
  model_type: ghost_marker
  xyz:
  - -7.13
  - 3.87
  - 0.11
- model_name: marker_2
  model_type: ghost_marker
  xyz:
  - -3.2
  - 11.65
  - 0.11
- model_name: marker_3
  model_type: ghost_marker
  xyz:
  - -10.73
  - 4.64
  - 0.11
- model_name: marker_4
  model_type: ghost_marker
  xyz:
  - -7.13
  - 9.38
  - 0.11
- model_name: marker_5
  model_type: ghost_marker
  xyz:
  - -12.82
  - 0.42
  - 0.11
- model_name: marker_6
  model_type: ghost_marker
  xyz:
  - -11.44
  - -1.14
  - 0.11
- model_name: marker_7
  model_type: ghost_marker
  xyz:
  - -11.92
  - 10.23
  - 0.11
- model_name: marker_8
  model_type: ghost_marker
  xyz:
  - -9.57
  - 0.99
  - 0.11
- model_name: base_inicial_hangthehook
  model_type: ghost_marker
  xyz:
  - 2.55
  - 9.86
  - 0.11
- model_name: mangueira_e_sustentacao
  model_type: truss_with_hose
  xyz:
  - 8.85
  - 1.76
  - 0.12
origin:
  altitude: 2
  latitude: -22.8627458
  longitude: -43.2297722
world_name: default
