drones:
- flight_time: 60
  model_name: x500_px4
  model_type: x500_px4
  payload:
  - model_name: gps
    model_type: gps
  - model_name: camera_frontal
    model_type: logitech_c920
    xyz:
    - 0.16
    - 0.0
    - -0.02
  - model_name: camera_inferior
    model_type: logitech_brio
    rpy:
    - 0.0
    - 1.5707
    - 0.0
    xyz:
    - 0.043
    - 0.0
    - -0.035
  - model_name: gancho
    model_type: gancho
    xyz:
    - 0.0
    - 0.0
    - -0.047
  xyz:
  - 0
  - 0
  - 0.5
objects:
- model_name: bouncing
  model_type: bouncing
  rpy:
  - 0.0
  - 0.0
  - 0.0
  xyz:
  - 0.0
  - 0.0
  - 0.1
- model_name: marker_1
  model_type: circulo_azul
  xyz:
  - 2.77
  - -0.44
  - 0.11
origin:
  altitude: 2
  latitude: -22.8627458
  longitude: -43.2297722
world_name: default
