drones:
- flight_time: 60
  model_name: x500_px4
  model_type: x500_px4
  payload:
  - model_name: gps
    model_type: gps
  - model_name: camera_frontal
    model_type: logitech_c920
    xyz:
    - 0.16
    - 0.0
    - -0.02
  - model_name: camera_inferior
    model_type: logitech_brio
    rpy:
    - 0.0
    - 1.5707
    - 0.0
    xyz:
    - 0.043
    - 0.0
    - -0.035
  xyz:
  - 0
  - 0
  - 0.5
  rpy:
  - 0
  - 0
  - 0.5
objects:
- model_name: hangthehook
  model_type: hangthehook
  rpy:
  - 0.0
  - 0.0
  - 0.5
  xyz:
  - 0.0
  - 0.0
  - 0.1
- model_name: base_inicial_hangthehook
  model_type: circulo_azul
  xyz:
  - 0.0
  - 0.0
  - 0.11
  rpy:
  - 0
  - 0
  - 0.5
- model_name: mangueira_e_sustentacao
  model_type: truss_with_hose
  rpy:
  - 0.0
  - 0.0
  - 2.21
  xyz:
  - -1.63
  - -2.31
  - 0.12
- model_name: fita
  model_type: fita
  xyz:
  - 0.0
  - 0.0
  - 0.1
origin:
  altitude: 2
  latitude: -22.8627458
  longitude: -43.2297722
world_name: default
