drones:
- flight_time: 60
  model_name: drone0
  model_type: x500_with_suction
  payload:
  - model_name: gps
    model_type: gps
  - model_name: gimbal
    model_type: gimbal_speed
    payload:
      model_name: camera
      model_type: hd_camera
  xyz:
  - -12.5
  - -10
  - 0.3
objects:
- model_name: eletroquad_arena
  model_type: eletroquad_arena
  rpy:
  - 0.0
  - 0.0
  - 0.0
  xyz:
  - 0.0
  - 0.0
  - 0.1
- model_name: base_inicial_slalom
  model_type: circulo_azul
  xyz:
  - -12.5
  - -10
  - 0.11
- model_name: barra_1
  model_type: barra_rosa
  xyz:
  - -8.44
  - -12.99
  - 0.1
- model_name: barra_2
  model_type: barra_azul
  xyz:
  - -0.53
  - -11.99
  - 0.1
- model_name: barra_3
  model_type: barra_preto_fosco
  xyz:
  - 6.89
  - -7.54
  - 0.1
- model_name: barra_4
  model_type: barra_vermelha
  xyz:
  - 11.48
  - -10.19
  - 0.1
- model_name: marker_1
  model_type: ghost_marker
  xyz:
  - -4.0
  - 11.49
  - 0.11
- model_name: marker_2
  model_type: ghost_marker
  xyz:
  - -5.77
  - 9.56
  - 0.11
- model_name: marker_3
  model_type: ghost_marker
  xyz:
  - -4.55
  - -2.82
  - 0.11
- model_name: marker_5
  model_type: ghost_marker
  xyz:
  - -11.94
  - 7.02
  - 0.11
- model_name: marker_6
  model_type: ghost_marker
  xyz:
  - -11.85
  - 9.08
  - 0.11
- model_name: marker_7
  model_type: ghost_marker
  xyz:
  - -9.28
  - 2.21
  - 0.11
- model_name: base_inicial_hangthehook
  model_type: ghost_marker
  xyz:
  - 5.27
  - 9.55
  - 0.11
- model_name: mangueira_e_sustentacao
  model_type: truss_with_hose
  xyz:
  - 9.61
  - 0.16
  - 0.12
origin:
  altitude: 2
  latitude: -22.8627458
  longitude: -43.2297722
world_name: eletroquad
