drones:
- flight_time: 60
  model_name: x500_px4
  model_type: x500_px4
  payload:
  - model_name: gps
    model_type: gps
  - model_name: camera
    model_type: hd_camera
    rpy:
    - 0.0
    - 0.0
    - 0.0
    xyz:
    - 0.04
    - 0.0
    - -0.1
  - model_name: gancho
    model_type: gancho
    xyz:
    - 0.0
    - 0.0
    - -0.05
  xyz:
  - -12.5
  - -10
  - 0.5
objects:
- model_name: eletroquad_arena
  model_type: eletroquad_arena
  rpy:
  - 0.0
  - 0.0
  - 0.0
  xyz:
  - 0.0
  - 0.0
  - 0.1
- model_name: base_inicial_slalom
  model_type: circulo_azul
  xyz:
  - -12.5
  - -10
  - 0.11
- model_name: barra_1
  model_type: barra_rosa
  object_bridges:
  - pose
  xyz:
  - -7.95
  - -7.49
  - 0.1
- model_name: barra_2
  model_type: barra_azul
  object_bridges:
  - pose
  xyz:
  - -2.79
  - -12.85
  - 0.1
- model_name: barra_3
  model_type: barra_preto_fosco
  object_bridges:
  - pose
  xyz:
  - 0.33
  - -12.92
  - 0.1
- model_name: barra_4
  model_type: barra_vermelha
  object_bridges:
  - pose
  xyz:
  - 9.73
  - -9.9
  - 0.1
- model_name: marker_1
  model_type: ghost_marker
  xyz:
  - -2.27
  - 5.14
  - 0.11
- model_name: marker_2
  model_type: ghost_marker
  xyz:
  - -9.11
  - 12.64
  - 0.11
- model_name: marker_3
  model_type: ghost_marker
  xyz:
  - -6.78
  - 10.95
  - 0.11
- model_name: marker_4
  model_type: ghost_marker
  xyz:
  - -3.23
  - -0.24
  - 0.11
- model_name: marker_5
  model_type: ghost_marker
  xyz:
  - -10.05
  - 8.61
  - 0.11
- model_name: marker_6
  model_type: ghost_marker
  xyz:
  - -2.44
  - -2.1
  - 0.11
- model_name: marker_7
  model_type: ghost_marker
  xyz:
  - -3.0
  - 7.54
  - 0.11
- model_name: marker_8
  model_type: ghost_marker
  xyz:
  - -8.33
  - -0.4
  - 0.11
- model_name: base_inicial_hangthehook
  model_type: ghost_marker
  xyz:
  - 7.61
  - 9.21
  - 0.11
- model_name: mangueira_e_sustentacao
  model_type: truss_with_hose
  xyz:
  - 11.89
  - -0.09
  - 0.12
origin:
  altitude: 2
  latitude: -22.8627458
  longitude: -43.2297722
world_name: default
