drones:
- flight_time: 60
  model_name: x500_px4
  model_type: x500_px4
  xyz:
  - 0
  - 0
  - 0.0
objects:
- model_name: hangthehook
  model_type: hangthehook
  rpy:
  - 0.0
  - 0.0
  - 0.0
  xyz:
  - 0.0
  - 0.0
  - 0.1
- model_name: base_inicial_hangthehook
  model_type: circulo_azul
  xyz:
  - 0.0
  - 0.0
  - 0.11
- model_name: mangueira_e_sustentacao
  model_type: truss_with_hose
  rpy:
  - 0.0
  - 0.0
  - 2.14
  xyz:
  - -2.97
  - 1.88
  - 0.12
- model_name: fita
  model_type: fita
  xyz:
  - 0.0
  - 0.0
  - 0.1
origin:
  altitude: 2
  latitude: -22.8627458
  longitude: -43.2297722
world_name: default
